CREATE DATABASE ATIVIDADE_DOIS_VIEWS;

USE ATIVIDADE_DOIS_VIEWS;

CREATE TABLE PRODUTOS (
    ID_PRODUTO INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    PRECO_UNICO DECIMAL(10, 2) NOT NULL,
    CATEGORIA VARCHAR(50) NOT NULL
);

INSERT INTO PRODUTOS (ID_PRODUTO, NOME, PRECO_UNICO, CATEGORIA) VALUES
(1, 'Café', 10.50, 'Comida'),
(2, 'Miojo', 5.25, 'Comida'),
(3, 'Prego', 8.75, 'Ferramenta');


CREATE TABLE ESTOQUE (
    ID_PRODUTO INT PRIMARY KEY,
    QUANT INT NOT NULL,
    FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTOS(ID_PRODUTO)
);

INSERT INTO ESTOQUE (ID_PRODUTO, QUANT) VALUES
(1, 15),
(2, 8),
(3, 3);

CREATE VIEW ESTOQUE_CRITICO AS
SELECT p.NOME AS NOME_PRODUTO, e.QUANT
FROM PRODUTOS p
JOIN ESTOQUE e ON p.ID_PRODUTO = e.ID_PRODUTO
WHERE e.QUANT < 10;

SELECT * FROM ESTOQUE_CRITICO;
