CREATE DATABASE ATIVIDADE_DOIS_TRIGGER;

USE ATIVIDADE_DOIS_TRIGGER;

CREATE TABLE CONTAS (
ID_CONTA INT PRIMARY KEY,
NOME VARCHAR (255) NOT NULL,
SALDO DECIMAL(10,2) NOT NULL
);

CREATE TABLE TRANSACOES (
ID_TRANSACAO INT PRIMARY KEY,
ID_CONTA INT, 
TIPO VARCHAR (255),
VALOR DECIMAL (10,2),
FOREIGN KEY (ID_CONTA) REFERENCES CONTAS (ID_CONTA)
);

DELIMITER //

CREATE TRIGGER ATUALIZAR_DADO
AFTER INSERT ON TRANSACOES
FOR EACH ROW
BEGIN
    IF NEW.TIPO = 'Entrada' THEN
        UPDATE CONTAS
        SET SALDO = SALDO + NEW.VALOR
        WHERE ID_CONTA = NEW.ID_CONTA;
    ELSE
        UPDATE CONTAS
        SET SALDO = SALDO - NEW.VALOR
        WHERE ID_CONTA = NEW.ID_CONTA;
    END IF;
END //
DELIMITER ;

INSERT INTO CONTAS (ID_CONTA, NOME, SALDO) VALUES
('1', "Gabriel Basto", 1000.00),
('2', "Daniel Santos", 958.00),
('3', "Jéssica", 654.00);

INSERT INTO TRANSACOES (ID_TRANSACAO, ID_CONTA, TIPO, VALOR) VALUES
('00001', '1', 'Entrada', 200.00),
('00002', '2', 'Saída', 100.00);

SELECT * FROM CONTAS;
