CREATE DATABASE ATIVIDADE_CINCO_VIEWS;

USE ATIVIDADE_CINCO_VIEWS;

CREATE TABLE CLIENTES (
    ID_CLIENTE INT PRIMARY KEY,
    NOME VARCHAR(255) NOT NULL,
    ENDERECO VARCHAR(255),
    CIDADE VARCHAR(100) NOT NULL
);

INSERT INTO CLIENTES (ID_CLIENTE, NOME, ENDERECO, CIDADE) VALUES
(1, 'Gabriel', 'Rua João Santo', 'São Paulo'),
(2, 'Jessica', 'Rua Bernardes Alice', 'Rio de Janeiro'),
(3, 'Daniel', 'Ruado Cabula', 'Salvador'),
(4, 'Selena', 'Rua Hollywood', 'Los Angeles');

CREATE TABLE PAGAMENTOS (
    ID_PAGAMENTO INT PRIMARY KEY,
    ID_CLIENTE INT,
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR_PAGAMENTO DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID_CLIENTE)
);

INSERT INTO PAGAMENTOS (ID_PAGAMENTO, ID_CLIENTE, DATA_PAGAMENTO, VALOR_PAGAMENTO) VALUES
(1, 4, '2023-11-11', 10000.00),
(2, 2, '2023-11-02', 2000.00),
(3, 1, '2023-10-26', 1100.00),
(4, 3, '2023-10-05', 3800.00),
(5, 2, '2023-10-01', 2500.00);

CREATE VIEW RELATORIO_PAGAMENTOS_CIDADE AS
SELECT
    c.CIDADE AS NOME_CIDADE,
    SUM(p.VALOR_PAGAMENTO) AS VALOR_TOTAL_PAGAMENTOS
FROM CLIENTES c
LEFT JOIN PAGAMENTOS p ON c.ID_CLIENTE = p.ID_CLIENTE
GROUP BY c.CIDADE;

SELECT * FROM RELATORIO_PAGAMENTOS_CIDADE;
