CREATE DATABASE ATIVIDADE_CINCO_TRIGGER;

USE ATIVIDADE_CINCO_TRIGGER;

CREATE TABLE ALUNOS (
    ID_ALUNO INT PRIMARY KEY AUTO_INCREMENT,
    NOME VARCHAR(255) NOT NULL,
    DATA_NASCIMENTO DATE NOT NULL,
    SERIE INT NOT NULL
);

INSERT INTO ALUNOS (NOME, DATA_NASCIMENTO, SERIE) VALUES
('Gabriel', '2015-03-10', 1),
('Jessica', '2014-07-22', 2),
('Daniel', '2013-01-05', 3);

CREATE TABLE MATRICULAS (
    ID_MATRICULA INT PRIMARY KEY AUTO_INCREMENT,
    ID_ALUNO INT,
    DATA_MATRICULA DATE NOT NULL,
    TIPO VARCHAR(50) NOT NULL,
    FOREIGN KEY (ID_ALUNO) REFERENCES ALUNOS(ID_ALUNO)
);

INSERT INTO MATRICULAS (ID_ALUNO, DATA_MATRICULA, TIPO) VALUES
(1, '2023-11-16', 'Ativa'),
(2, '2023-11-16', 'Ativa'),
(3, '2023-11-16', 'Ativa');

DELIMITER //

CREATE TRIGGER VERIFICAR_IDADE
BEFORE INSERT ON MATRICULAS
FOR EACH ROW
BEGIN
    DECLARE IDADE_ALUNO INT;
    DECLARE SERIE_ATUAL INT;

    SELECT TIMESTAMPDIFF(YEAR, ALUNOS.DATA_NASCIMENTO, NEW.DATA_MATRICULA) INTO IDADE_ALUNO
    FROM ALUNOS
    WHERE ALUNOS.ID_ALUNO = NEW.ID_ALUNO;

    SELECT ALUNOS.SERIE INTO SERIE_ATUAL
    FROM ALUNOS
    WHERE ALUNOS.ID_ALUNO = NEW.ID_ALUNO;

    IF SERIE_ATUAL = 1 AND IDADE_ALUNO < 6 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Aluno não atende aos requisitos de idade para a série 1.';
    ELSE IF SERIE_ATUAL = 2 AND IDADE_ALUNO < 7 THEN
        SIGNAL SQLSTATE '45000'
        SET MESSAGE_TEXT = 'Aluno não atende aos requisitos de idade para a série 2.';
    END IF;
END;
//

DELIMITER ;

INSERT INTO MATRICULAS (ID_ALUNO, DATA_MATRICULA, TIPO) VALUES
(2, '2020-11-06', 'Ativa');
