CREATE DATABASE ATIVIDADE_UM_;

USE ATIVIDADE_UM_;

CREATE TABLE LIVROS (
    ID_LIVRO INT PRIMARY KEY,
    TITULO VARCHAR(255),
    AUTOR VARCHAR(255),
    QUANT_ESTOQUE INT
);

INSERT INTO LIVROS (ID_LIVRO, TITULO, AUTOR, QUANT_ESTOQUE)
VALUES (1, 'Crepúsculo', 'Stephenie Meyer', 19),
       (2, 'Jogos Vorazes', 'Suzanne Collins', 32),
       (3, 'Maze Runner', 'James Dashner', 17);


CREATE TABLE EMPRESTIMOS (
    ID_EMPRESTIMOS INT PRIMARY KEY,
    ID_LIVRO INT,
    DATA_EMPRESTIMO DATETIME,
    DATA_DEVOLUCAO DATETIME,
    FOREIGN KEY (ID_LIVRO) REFERENCES LIVROS(ID_LIVRO)
);

DELIMITER //

CREATE TRIGGER ATUALIZAR_ESTOQUE
AFTER INSERT ON EMPRESTIMOS
FOR EACH ROW
BEGIN
    UPDATE LIVROS
    SET QUANT_ESTOQUE = QUANT_ESTOQUE - 1
    WHERE ID_LIVRO = NEW.ID_LIVRO;
END//

DELIMITER ;

INSERT INTO EMPRESTIMOS (ID_EMPRESTIMOS, ID_LIVRO, DATA_EMPRESTIMO, DATA_DEVOLUCAO)
VALUES (1, 3, NOW(), NOW() + INTERVAL 7 DAY);

SELECT * FROM EMPRESTIMOS;
